use chrono::{DateTime, Utc};
use domain::{DomainError, Media, MediaStatus};
use sqlx::PgPool;
use thiserror::Error;
use uuid::Uuid;

#[derive(Debug, Error)]
pub enum MediaRepoError {
    #[error(transparent)]
    Domain(#[from] DomainError),
    #[error(transparent)]
    Db(#[from] sqlx::Error),
}

pub struct MediaRecord {
    pub media: Media,
    pub created_at: DateTime<Utc>,
}

/// Reserves quota (atomic `UPDATE ... WHERE ... RETURNING`, so two
/// concurrent uploads can't both pass a stale count-then-act check) and
/// inserts a `pending` media row in the same transaction. `id` and
/// `object_key` are generated by the caller (the object key embeds the
/// media id, so it has to exist before this call, not after).
#[allow(clippy::too_many_arguments)]
pub async fn reserve_and_create_pending(
    pool: &PgPool,
    id: Uuid,
    container_id: Uuid,
    uploader_id: &str,
    object_key: &str,
    filename: &str,
    content_type: &str,
    size_bytes: i64,
) -> Result<Media, MediaRepoError> {
    let mut tx = pool.begin().await?;

    let reserved = sqlx::query_scalar!(
        "UPDATE container
         SET storage_bytes = storage_bytes + $2,
             media_count = media_count + 1
         WHERE id = $1
           AND storage_bytes + $2 <= storage_limit
           AND media_count + 1 <= media_limit
         RETURNING id",
        container_id,
        size_bytes
    )
    .fetch_optional(&mut *tx)
    .await?;

    if reserved.is_none() {
        return Err(DomainError::QuotaExceeded.into());
    }

    sqlx::query!(
        "INSERT INTO media (id, container_id, uploader_id, object_key, filename, content_type, size_bytes, status)
         VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')",
        id,
        container_id,
        uploader_id,
        object_key,
        filename,
        content_type,
        size_bytes
    )
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    Ok(Media {
        id,
        container_id,
        uploader_id: uploader_id.to_string(),
        object_key: object_key.to_string(),
        filename: filename.to_string(),
        caption: None,
        content_type: content_type.to_string(),
        size_bytes,
        status: MediaStatus::Pending,
    })
}

pub async fn get_by_id(pool: &PgPool, id: Uuid) -> Result<Option<MediaRecord>, sqlx::Error> {
    let row = sqlx::query!(
        "SELECT id, container_id, uploader_id, object_key, filename, caption, content_type, size_bytes, status, created_at
         FROM media WHERE id = $1",
        id
    )
    .fetch_optional(pool)
    .await?;

    Ok(row.and_then(|r| {
        let status = r.status.parse::<MediaStatus>().ok()?;
        Some(MediaRecord {
            media: Media {
                id: r.id,
                container_id: r.container_id,
                uploader_id: r.uploader_id,
                object_key: r.object_key,
                filename: r.filename,
                caption: r.caption,
                content_type: r.content_type,
                size_bytes: r.size_bytes,
                status,
            },
            created_at: r.created_at,
        })
    }))
}

/// Keyset-paginated by id (UUIDv7 is time-sortable), newest first. Only
/// `ready` media is listed — `pending` rows are upload-in-progress
/// bookkeeping, not visible content.
pub async fn list_for_container(
    pool: &PgPool,
    container_id: Uuid,
    cursor: Option<Uuid>,
    limit: i64,
    media_type: Option<&str>,
    uploader_id: Option<&str>,
) -> Result<Vec<MediaRecord>, sqlx::Error> {
    let rows = sqlx::query!(
        "SELECT id, container_id, uploader_id, object_key, filename, caption, content_type, size_bytes, status, created_at
         FROM media
         WHERE container_id = $1
           AND status = 'ready'
           AND ($2::uuid IS NULL OR id < $2)
           AND ($3::text IS NULL OR content_type LIKE $3 || '/%')
           AND ($4::text IS NULL OR uploader_id = $4)
         ORDER BY id DESC
         LIMIT $5",
        container_id,
        cursor,
        media_type,
        uploader_id,
        limit
    )
    .fetch_all(pool)
    .await?;

    Ok(rows
        .into_iter()
        .filter_map(|r| {
            let status = r.status.parse::<MediaStatus>().ok()?;
            Some(MediaRecord {
                media: Media {
                    id: r.id,
                    container_id: r.container_id,
                    uploader_id: r.uploader_id,
                    object_key: r.object_key,
                    filename: r.filename,
                    caption: r.caption,
                    content_type: r.content_type,
                    size_bytes: r.size_bytes,
                    status,
                },
                created_at: r.created_at,
            })
        })
        .collect())
}

/// Flips a `pending` row to `ready`. No-op (returns `false`) if the row
/// is missing or already `ready` — the complete endpoint treats either
/// as an idempotent success rather than an error.
pub async fn mark_ready(pool: &PgPool, id: Uuid) -> Result<bool, sqlx::Error> {
    let result = sqlx::query!(
        "UPDATE media SET status = 'ready' WHERE id = $1 AND status = 'pending'",
        id
    )
    .execute(pool)
    .await?;

    Ok(result.rows_affected() > 0)
}

async fn delete_with_status(
    pool: &PgPool,
    id: Uuid,
    status: &str,
) -> Result<Option<Media>, sqlx::Error> {
    let mut tx = pool.begin().await?;

    let row = sqlx::query!(
        "DELETE FROM media WHERE id = $1 AND status = $2
         RETURNING container_id, uploader_id, object_key, filename, caption, content_type, size_bytes",
        id,
        status
    )
    .fetch_optional(&mut *tx)
    .await?;

    let Some(row) = row else {
        return Ok(None);
    };

    sqlx::query!(
        "UPDATE container SET storage_bytes = storage_bytes - $2, media_count = media_count - 1 WHERE id = $1",
        row.container_id,
        row.size_bytes
    )
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    let Ok(status) = status.parse::<MediaStatus>() else {
        return Ok(None);
    };

    Ok(Some(Media {
        id,
        container_id: row.container_id,
        uploader_id: row.uploader_id,
        object_key: row.object_key,
        filename: row.filename,
        caption: row.caption,
        content_type: row.content_type,
        size_bytes: row.size_bytes,
        status,
    }))
}

/// Deletes a still-`pending` row (the client abandoned the upload before
/// calling complete) and releases the quota reserved for it.
pub async fn abort_pending(pool: &PgPool, id: Uuid) -> Result<Option<Media>, sqlx::Error> {
    delete_with_status(pool, id, "pending").await
}

/// Deletes a `ready` media item and releases its quota.
pub async fn delete_ready(pool: &PgPool, id: Uuid) -> Result<Option<Media>, sqlx::Error> {
    delete_with_status(pool, id, "ready").await
}

/// Updates filename/caption on a `ready` media item. `None` leaves a
/// field unchanged (there's no way to explicitly clear `caption` back to
/// null this way — an accepted MVP limitation, not a bug).
pub async fn update_metadata(
    pool: &PgPool,
    id: Uuid,
    filename: Option<&str>,
    caption: Option<&str>,
) -> Result<Option<MediaRecord>, sqlx::Error> {
    let row = sqlx::query!(
        "UPDATE media
         SET filename = COALESCE($2, filename),
             caption = COALESCE($3, caption)
         WHERE id = $1 AND status = 'ready'
         RETURNING id, container_id, uploader_id, object_key, filename, caption, content_type, size_bytes, status, created_at",
        id,
        filename,
        caption
    )
    .fetch_optional(pool)
    .await?;

    Ok(row.and_then(|r| {
        let status = r.status.parse::<MediaStatus>().ok()?;
        Some(MediaRecord {
            media: Media {
                id: r.id,
                container_id: r.container_id,
                uploader_id: r.uploader_id,
                object_key: r.object_key,
                filename: r.filename,
                caption: r.caption,
                content_type: r.content_type,
                size_bytes: r.size_bytes,
                status,
            },
            created_at: r.created_at,
        })
    }))
}
