/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type {
  ContainerDto,
  ContainerListResponse,
  ContainerUsageResponse,
  CreateContainerRequest,
  SetLockRequest,
  ShareLinkResponse,
  UpdateContainerRequest
} from '../models';

import { customInstance } from '../../axios-instance';



  export const getContainers = () => {
const listContainers = (

 ) => {
      return customInstance<ContainerListResponse>(
      {url: `/containers`, method: 'GET'
    },
      );
    }
  const createContainer = (
    createContainerRequest: CreateContainerRequest,
 ) => {
      return customInstance<ContainerDto>(
      {url: `/containers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createContainerRequest
    },
      );
    }
  const getContainer = (
    containerId: string,
 ) => {
      return customInstance<ContainerDto>(
      {url: `/containers/${containerId}`, method: 'GET'
    },
      );
    }
  const deleteContainer = (
    containerId: string,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}`, method: 'DELETE'
    },
      );
    }
  const updateContainer = (
    containerId: string,
    updateContainerRequest: UpdateContainerRequest,
 ) => {
      return customInstance<ContainerDto>(
      {url: `/containers/${containerId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateContainerRequest
    },
      );
    }
  const setContainerLock = (
    containerId: string,
    setLockRequest: SetLockRequest,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}/lock`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setLockRequest
    },
      );
    }
  const getShareLink = (
    containerId: string,
 ) => {
      return customInstance<ShareLinkResponse>(
      {url: `/containers/${containerId}/share-link`, method: 'GET'
    },
      );
    }
  const rotateShareLink = (
    containerId: string,
 ) => {
      return customInstance<ShareLinkResponse>(
      {url: `/containers/${containerId}/share-link/rotate`, method: 'POST'
    },
      );
    }
  const getContainerUsage = (
    containerId: string,
 ) => {
      return customInstance<ContainerUsageResponse>(
      {url: `/containers/${containerId}/usage`, method: 'GET'
    },
      );
    }
  return {listContainers,createContainer,getContainer,deleteContainer,updateContainer,setContainerLock,getShareLink,rotateShareLink,getContainerUsage}};
export type ListContainersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['listContainers']>>>
export type CreateContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['createContainer']>>>
export type GetContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['getContainer']>>>
export type DeleteContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['deleteContainer']>>>
export type UpdateContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['updateContainer']>>>
export type SetContainerLockResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['setContainerLock']>>>
export type GetShareLinkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['getShareLink']>>>
export type RotateShareLinkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['rotateShareLink']>>>
export type GetContainerUsageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['getContainerUsage']>>>
