/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type {
  ContainerDto,
  ContainerListResponse,
  CreateContainerRequest
} from '../models';

import { customInstance } from '../../axios-instance';



  export const getContainers = () => {
const listContainers = (

 ) => {
      return customInstance<ContainerListResponse>(
      {url: `/containers`, method: 'GET'
    },
      );
    }
  const createContainer = (
    createContainerRequest: CreateContainerRequest,
 ) => {
      return customInstance<ContainerDto>(
      {url: `/containers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createContainerRequest
    },
      );
    }
  const getContainer = (
    containerId: string,
 ) => {
      return customInstance<ContainerDto>(
      {url: `/containers/${containerId}`, method: 'GET'
    },
      );
    }
  return {listContainers,createContainer,getContainer}};
export type ListContainersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['listContainers']>>>
export type CreateContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['createContainer']>>>
export type GetContainerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getContainers>['getContainer']>>>
