/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface AuthSessionDto {
  /** @nullable */
  activeOrganizationId?: string | null;
  /** ISO-8601 timestamp. */
  createdAt: string;
  /** ISO-8601 timestamp. */
  expiresAt: string;
  id: string;
  /** @nullable */
  impersonatedBy?: string | null;
  /** @nullable */
  ipAddress?: string | null;
  token: string;
  /** ISO-8601 timestamp. */
  updatedAt: string;
  /** @nullable */
  userAgent?: string | null;
  userId: string;
}
