/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface AuthUserDto {
  /**
     * ISO-8601 timestamp, if the ban is time-limited.
     * @nullable
     */
  banExpires?: string | null;
  /** @nullable */
  banReason?: string | null;
  banned: boolean;
  /** ISO-8601 timestamp. */
  createdAt: string;
  /** @nullable */
  displayUsername?: string | null;
  /** @nullable */
  email?: string | null;
  emailVerified: boolean;
  id: string;
  /** @nullable */
  image?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  role?: string | null;
  twoFactorEnabled: boolean;
  /** ISO-8601 timestamp. */
  updatedAt: string;
  /** @nullable */
  username?: string | null;
}
