/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface ContainerDto {
  id: string;
  is_locked: boolean;
  is_public: boolean;
  name: string;
  role: string;
}
