/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type { ContainerDto } from './containerDto';

export interface ContainerListResponse {
  containers: ContainerDto[];
}
