/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface ContainerUsageResponse {
  media_count: number;
  media_limit: number;
  member_count: number;
  storage_bytes: number;
  storage_limit: number;
}
