/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface CreateUploadRequest {
  content_type: string;
  filename: string;
  size_bytes: number;
}
