/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface DownloadUrlResponse {
  /** @minimum 0 */
  expires_in_seconds: number;
  url: string;
}
