/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export type GetMediaParams = {
/**
 * Anonymous View access via a container's share link
 */
share_token?: string;
};
