/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type { AuthSessionDto } from './authSessionDto';
import type { AuthUserDto } from './authUserDto';

export interface GetSessionResponse {
  session: AuthSessionDto;
  user: AuthUserDto;
}
