/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export type ListMediaParams = {
/**
 * Keyset cursor: id of the last item from the previous page
 */
cursor?: string;
/**
 * Page size, capped at 100
 */
limit?: number;
/**
 * Filter by content-type prefix: image or video
 */
type?: string;
/**
 * Filter by uploader user id
 */
uploader?: string;
};
