/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type { MediaDto } from './mediaDto';

export interface MediaListResponse {
  media: MediaDto[];
  /** @nullable */
  next_cursor?: string | null;
}
