/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface MediaDto {
  /** @nullable */
  caption?: string | null;
  content_type: string;
  created_at: string;
  filename: string;
  id: string;
  size_bytes: number;
  status: string;
  uploader_id: string;
}
