/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface MemberDto {
  /** @nullable */
  email?: string | null;
  joined_at: string;
  /** @nullable */
  name?: string | null;
  role: string;
  user_id: string;
}
