/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface MeResponse {
  /** @nullable */
  ban_expires?: string | null;
  /** @nullable */
  ban_reason?: string | null;
  banned: boolean;
  /** @nullable */
  email?: string | null;
  email_verified: boolean;
  id: string;
  /** @nullable */
  image?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  username?: string | null;
}
