/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type { AuthUserDto } from './authUserDto';

export interface SignInEmailResponse {
  redirect: boolean;
  token: string;
  /** @nullable */
  url?: string | null;
  user: AuthUserDto;
}
