/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateMemberRoleRequest {
  /**
     * "editor" or "viewer" — use POST .../transfer-ownership to change
     * who the owner is, this endpoint rejects "owner".
     */
  role: string;
}
