/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateMediaRequest {
  /** @nullable */
  caption?: string | null;
  /** @nullable */
  filename?: string | null;
}
