/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateContainerRequest {
  /** @nullable */
  media_limit?: number | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  storage_limit_bytes?: number | null;
}
