/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type {
  AddAllowlistEntryRequest,
  AllowlistResponse
} from '../models';

import { customInstance } from '../../axios-instance';



  export const getInvites = () => {
const listAllowlist = (
    containerId: string,
 ) => {
      return customInstance<AllowlistResponse>(
      {url: `/containers/${containerId}/edit-allowlist`, method: 'GET'
    },
      );
    }
  const addAllowlistEntry = (
    containerId: string,
    addAllowlistEntryRequest: AddAllowlistEntryRequest,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}/edit-allowlist`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addAllowlistEntryRequest
    },
      );
    }
  const deleteAllowlistEntry = (
    containerId: string,
    email: string,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}/edit-allowlist/${email}`, method: 'DELETE'
    },
      );
    }
  return {listAllowlist,addAllowlistEntry,deleteAllowlistEntry}};
export type ListAllowlistResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInvites>['listAllowlist']>>>
export type AddAllowlistEntryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInvites>['addAllowlistEntry']>>>
export type DeleteAllowlistEntryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInvites>['deleteAllowlistEntry']>>>
