/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type {
  AddAllowlistEntryRequest,
  AllowlistResponse,
  SharePreviewResponse
} from '../models';

import { customInstance } from '../../axios-instance';



  export const getInvites = () => {
const listAllowlist = (
    containerId: string,
 ) => {
      return customInstance<AllowlistResponse>(
      {url: `/containers/${containerId}/edit-allowlist`, method: 'GET'
    },
      );
    }
  const addAllowlistEntry = (
    containerId: string,
    addAllowlistEntryRequest: AddAllowlistEntryRequest,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}/edit-allowlist`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addAllowlistEntryRequest
    },
      );
    }
  const deleteAllowlistEntry = (
    containerId: string,
    email: string,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}/edit-allowlist/${email}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary Public, no auth, no membership required — this is the landing-page
preview a share link resolves to, not the media grid itself (that's
`GET /containers/{cid}/media?share_token=...`, gated by
`ContainerViewAccess`). Rate-limited the same as every other route,
via the global governor layer in router.rs.
 */
const resolveShareToken = (
    token: string,
 ) => {
      return customInstance<SharePreviewResponse>(
      {url: `/invites/${token}`, method: 'GET'
    },
      );
    }
  return {listAllowlist,addAllowlistEntry,deleteAllowlistEntry,resolveShareToken}};
export type ListAllowlistResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInvites>['listAllowlist']>>>
export type AddAllowlistEntryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInvites>['addAllowlistEntry']>>>
export type DeleteAllowlistEntryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInvites>['deleteAllowlistEntry']>>>
export type ResolveShareTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getInvites>['resolveShareToken']>>>
