/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateUploadRequest,
  CreateUploadResponse,
  DownloadUrlResponse,
  ListMediaParams,
  MediaDto,
  MediaListResponse,
  UpdateMediaRequest
} from '../models';

import { customInstance } from '../../axios-instance';



  export const getMedia = () => {
const listMedia = (
    containerId: string,
    params?: ListMediaParams,
 ) => {
      return customInstance<MediaListResponse>(
      {url: `/containers/${containerId}/media`, method: 'GET',
        params
    },
      );
    }
  const getMedia = (
    containerId: string,
    mediaId: string,
 ) => {
      return customInstance<MediaDto>(
      {url: `/containers/${containerId}/media/${mediaId}`, method: 'GET'
    },
      );
    }
  const deleteMedia = (
    containerId: string,
    mediaId: string,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}/media/${mediaId}`, method: 'DELETE'
    },
      );
    }
  const updateMedia = (
    containerId: string,
    mediaId: string,
    updateMediaRequest: UpdateMediaRequest,
 ) => {
      return customInstance<MediaDto>(
      {url: `/containers/${containerId}/media/${mediaId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateMediaRequest
    },
      );
    }
  const downloadMedia = (
    containerId: string,
    mediaId: string,
 ) => {
      return customInstance<DownloadUrlResponse>(
      {url: `/containers/${containerId}/media/${mediaId}/download`, method: 'GET'
    },
      );
    }
  const createUpload = (
    containerId: string,
    createUploadRequest: CreateUploadRequest,
 ) => {
      return customInstance<CreateUploadResponse>(
      {url: `/containers/${containerId}/uploads`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUploadRequest
    },
      );
    }
  const abortUpload = (
    containerId: string,
    mediaId: string,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}/uploads/${mediaId}`, method: 'DELETE'
    },
      );
    }
  const completeUpload = (
    containerId: string,
    mediaId: string,
 ) => {
      return customInstance<MediaDto>(
      {url: `/containers/${containerId}/uploads/${mediaId}/complete`, method: 'POST'
    },
      );
    }
  return {listMedia,getMedia,deleteMedia,updateMedia,downloadMedia,createUpload,abortUpload,completeUpload}};
export type ListMediaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMedia>['listMedia']>>>
export type GetMediaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMedia>['getMedia']>>>
export type DeleteMediaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMedia>['deleteMedia']>>>
export type UpdateMediaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMedia>['updateMedia']>>>
export type DownloadMediaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMedia>['downloadMedia']>>>
export type CreateUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMedia>['createUpload']>>>
export type AbortUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMedia>['abortUpload']>>>
export type CompleteUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMedia>['completeUpload']>>>
