#!/usr/bin/env sh

FRONTEND_CHANGED=$(git diff --cached --name-only -- frontend)
if [ -n "$FRONTEND_CHANGED" ]; then
  echo "Running frontend checks..."
  (cd frontend && bun run check && bun run typecheck) || exit 1
fi

BACKEND_CHANGED=$(git diff --cached --name-only -- backend)
if [ -n "$BACKEND_CHANGED" ]; then
  echo "Running backend checks..."
  (git add . && cd backend && cargo fmt --all -- --check && cargo clippy --all-targets --all-features -- -D warnings) || exit 1
fi
