/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type {
  MeResponse
} from '../models';

import { customInstance } from '../../axios-instance';



  export const getAuth = () => {
const getMe = (

 ) => {
      return customInstance<MeResponse>(
      {url: `/me`, method: 'GET'
    },
      );
    }
  return {getMe}};
export type GetMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['getMe']>>>
