import axios, { type AxiosError, type AxiosRequestConfig } from "axios";

// The actual axios instance — this is where interceptors live.
// Everything generated by orval calls through this, so an auth header,
// a 401-refresh flow, request logging, etc. all go here, once, not
// per-call.
export const AXIOS_INSTANCE = axios.create({
  baseURL: import.meta.env.VITE_API_BASE_URL,
});

AXIOS_INSTANCE.interceptors.request.use((config) => {
  // e.g. attach an auth token once better-auth is wired up:
  // config.headers.Authorization = `Bearer ${getToken()}`;
  return config;
});

AXIOS_INSTANCE.interceptors.response.use(
  (response) => response,
  (error) => {
    // e.g. redirect to login on 401, log to an error tracker, etc.
    return Promise.reject(error);
  }
);

// orval calls every generated function through this "mutator" instead
// of axios directly — it's the seam that lets orval-generated code use
// *your* configured instance (baseURL + interceptors) rather than a
// bare axios.request with no config.
export const customInstance = <T>(config: AxiosRequestConfig): Promise<T> => {
  const source = axios.CancelToken.source();
  const promise = AXIOS_INSTANCE({
    ...config,
    cancelToken: source.token,
  }).then(({ data }) => data);

  // Lets React Query (later) cancel in-flight requests on unmount —
  // harmless no-op until you actually wire up useQuery.
  // @ts-expect-error — orval's convention, not a real AxiosPromise field
  promise.cancel = () => {
    source.cancel("Query was cancelled");
  };

  return promise;
};

export type ErrorType<Error> = AxiosError<Error>;
