/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */
import type {
  MemberListResponse,
  MemberRoleResponse,
  TransferOwnershipRequest,
  UpdateMemberRoleRequest
} from '../models';

import { customInstance } from '../../axios-instance';



  export const getMembers = () => {
const listMembers = (
    containerId: string,
 ) => {
      return customInstance<MemberListResponse>(
      {url: `/containers/${containerId}/members`, method: 'GET'
    },
      );
    }
  const removeMember = (
    containerId: string,
    userId: string,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}/members/${userId}`, method: 'DELETE'
    },
      );
    }
  const updateMemberRole = (
    containerId: string,
    userId: string,
    updateMemberRoleRequest: UpdateMemberRoleRequest,
 ) => {
      return customInstance<MemberRoleResponse>(
      {url: `/containers/${containerId}/members/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateMemberRoleRequest
    },
      );
    }
  const transferOwnership = (
    containerId: string,
    transferOwnershipRequest: TransferOwnershipRequest,
 ) => {
      return customInstance<void>(
      {url: `/containers/${containerId}/transfer-ownership`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: transferOwnershipRequest
    },
      );
    }
  return {listMembers,removeMember,updateMemberRole,transferOwnership}};
export type ListMembersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMembers>['listMembers']>>>
export type RemoveMemberResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMembers>['removeMember']>>>
export type UpdateMemberRoleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMembers>['updateMemberRole']>>>
export type TransferOwnershipResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMembers>['transferOwnership']>>>
