/**
 * Generated by orval 🍺
 * Do not edit manually.
 * remera-api-docs
 * OpenAPI spec version: 0.1.0
 */

import { customInstance } from "../../axios-instance";
import type { HealthResponse } from "../models";

export const getMeta = () => {
  const getSlash = () => {
    return customInstance<void>({ url: `/`, method: "GET" });
  };
  const healthz = () => {
    return customInstance<HealthResponse>({ url: `/healthz`, method: "GET" });
  };
  return { getSlash, healthz };
};
export type GetSlashResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMeta>["getSlash"]>>
>;
export type HealthzResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMeta>["healthz"]>>
>;
